sonar.projectKey=a-aliev-dev_Game-Project-Scala
sonar.organization=a-aliev-dev

sonar.projectName=game-project
sonar.sources=src/main/scala
sonar.tests=src/test/scala

sonar.sourceEncoding=UTF-8

sonar.scala.coverage.reportPaths=target/scala-3.8.3/scoverage-report/scoverage.xml